### ISSUE TITLE
API Version 2: Failed to parse JSON response string with 'INVALID_ARGUMENT

### ISSUE THREAD

**Issue by loretoparisi** [actions-on-google/actions-on-google-nodejs#114]
Hi,
I have this error in the assistant console

```
API Version 2: Failed to parse JSON response string with 'INVALID_ARGUMENT' error: "(response_metadata.status.details[0]): invalid value Missing @type for any field in google.actions.v2.AppResponse for type Any".
```

But I have setup the API Version 2 to off in the Dialogflow settings, since this node.js client does not currently supports the Dialogflow v2 api. How to force the v2 then?

**Comment by Fleker** [comment]
Can you specify the `actions-on-google` npm version and the code snippet you're trying to run?

**Comment by loretoparisi** [comment]
@Fleker Hello, I have used the latest alpha-2 on the npm module.

**Comment by Edo78** [comment]
I got the very same error in the simulator when my backend server isn't running or when it doesn't respond in time ...
Are you sure that your server is up and running and that it reply in time?

**Comment by loretoparisi** [comment]
@Fleker @Edo78 is is possibile that this is a simulator issue? I got this error in the simulator as well...

**Comment by smishra2** [comment]
@loretoparisi The new alpha release of the client library does support Dialogflow's V2 API :)

**Comment by Canain** [comment]
@Anshini-Singh since you are using the v1 client library, and firebase functions 1.0.0, you need to change these parts of your code:

Instead of
```
const DialogflowApp = require('actions-on-google');
```
 It should be
```
const { DialogflowApp } = require('actions-on-google');
```

Your original code should throw an error when called since the wildcard import of  `actions-on-google` is not a class and is instantiable. Check your firebase console function logs for errors.

For Firebase Functions 1.0.0, you need to remove this part:
```
admin.initializeApp(functions.config().firebase);
```

**Comment by Anshini-Singh** [comment]
@Canain It worked fine, Thanks
