### ISSUE TITLE
Failed to parse the dialog flow response into AppResponse because of empty speech response

### ISSUE THREAD

**Issue by loretoparisi** [actions-on-google/actions-on-google-nodejs#117]
I'm getting this error in my test Dialogflow app (v2) plus Dialogflow fulfillment using the simplest example depicted here: **https://github.com/dialogflow/fulfillment-webhook-nodejs/blob/master/functions/index.js**

When using a external service api call like:

```javascript
var get = (host,path) => new Promise((resolve, reject) => {
    var options = {
        headers: {},
        hostname: host,
        path: path,
        method: 'GET'
    };
    var request = require('http').get(options, function (response) {
        var body = '';
        response.on('data', function (d) {
            body += d;
        });
        response.on('end', function () {
            resolve(body);
        });
    });
    request.on('error', function (err) { console.error(err); reject(error); });
    request.end();
});

get(myHost,myPath)
.then(res => agent.add(res) )
.catch(error => agent.add("Sorry there was an error") )
```

The api call works, and I can see the api response request headers and results. But as soon as I call `agent.add(res)` I get that error, while of course if I remove that api call and directly output a message via `agent.add` it works. I have also the default explicit invocation correctly configured.

I have solved configuration problems already, related to the issue depicted here https://github.com/actions-on-google/actions-on-google-nodejs/issues/79 and here https://github.com/actions-on-google/actions-on-google-nodejs/issues/97

**Comment by Canain** [comment]
Hi, this is more of a question about [Dialogflow's Fulfillment Library](https://github.com/dialogflow/dialogflow-fulfillment-nodejs) which is what you are using.

You should ask on StackOverflow or if there's an issue, open one on their [issues page](https://github.com/dialogflow/dialogflow-fulfillment-nodejs/issues) to get better help.

But, from what I can guess is that since you have an async task, you aren't returning the promise in the request.

You need to do `return get(myHost, myPath)` in order for the Dialogflow fulfillment library to keep track of your request and help construct it for you. When you return a promise, their library will [detect that it's an async task and wait for the promise to resolve](https://github.com/dialogflow/dialogflow-fulfillment-nodejs/blob/40c8a456569e1b2950f43e9064a1aed17afc835c/src/dialogflow-fulfillment.js#L241) so it can send the request correctly.

Closing this issue as it's not about this library. Feel free to ask for more details, but you should ask in the appropriate places as mentioned earlier.

**Comment by loretoparisi** [comment]
**[UPDATE]**
I confirm that that missing *return* statement was the error:

```javascript
return get(myHost,myPath)
.then(res => agent.add(res) )
.catch(error => agent.add("Sorry there was an error") )
```

Thanks for point this out!
