### ISSUE TITLE
how to adjust volume / intercept "previous" using MediaObject responses?

### ISSUE THREAD

**Issue by nealrs** [actions-on-google/actions-on-google-nodejs#146]
I'm building an Action using the longform media player / mediaObjects responses. However, I'm having 2 big issues: 

1. 'Previous' is intercepted by Asst & restarts the current audio clip, rather than entering into my fulfillment's code (so I can jump backwards to a previous one). 'Next' is passed correctly to my fulfillment. => Interestingly, this only happens on a physical device. In the Actions simulator, previous is passed back correctly to the fulfillment.

2. More frustratingly, [voice volume commands](https://support.google.com/googlehome/answer/7072489?hl=en) are _NOT_ intercepted by Asst, and the recognized test *does* get passed to the fulfillment. I was hoping Google Home would intercept these appropriately, (like with Pause/Resume), but they are not, so they end up throwing fallback intents in my action & I can not control playback volume. Is it true that 3rd party actions can not control volume?

Appreciate any help clearing this up / pointers to docs I missed. Thanks!

**Comment by davidfedor** [comment]
Handling next/previous and volume up/down are the top requests from my users, as well as a big source of confusion for them. 

Would love to have platform support for this, particularly since the Google Home hub shows next/previous buttons on screen which currently can do nothing while my MediaObject is playing!

**Comment by nealrs** [comment]
It's been ~11 months, but I'm still having this issue.

**Comment by lucaswadedavis** [comment]
Thanks for all your comments everybody. While the platform doesn't currently support what you've asked for, we have registered these feature requests with our product managers.

I'm closing the issue for now, since we've raised it internally, but if you notice any bugs with the features we do explicitly support - or if you have any other feature requests - please feel free to open a new issue.

**Comment by lucaswadedavis** [comment]
https://stackoverflow.com/questions/46283257/how-to-control-google-home-volume-from-actions-on-google
