### ISSUE TITLE
Say something & followup

### ISSUE THREAD

**Issue by westlakem** [actions-on-google/actions-on-google-nodejs#150]
I'm trying to inform my customer before moving them to a followup intent.  I can call each intent individually, and when I call Injured it takes me to the `"Send Care Package"` intent, but it never responds with the `"I'm sorry to hear that"` text.  I've also tried with `conv.close()` but I can't get it to say something before forwarding to the 2nd intent.

```
app.intent('Injured', conv => {
    conv.ask("I'm sorry to hear that")
    conv.followup('event2')
})

app.intent('Send Care Package', conv => {
    //send care package
    conv.close("I'm sending you a care package")
})
```

**Comment by Canain** [comment]
That's the intended behavior for followup. See the Dialogflow docs about [Invoking Event from Webhook](https://dialogflow.com/docs/events#invoking_event_from_webhook) for more info.

It's more like a redirect to another intent so that new intent can handle the response. If you want to send extra info to that event, you would need to store it in contexts or `conv.data`.
