### ISSUE TITLE
Static reprompts in the v2 library?

### ISSUE THREAD

**Issue by joelhegg** [actions-on-google/actions-on-google-nodejs#155]
I don't see this discussed in https://developers.google.com/actions/reference/nodejs/lib-v1-migration. In the v1 library we used `app.buildInputPrompt()` to statically specify the no-input prompts. How do we do this in v2?

https://developers.google.com/actions/assistant/reprompts mentions system-default and static reprompts, but it's pretty sparse. Most of the focus is on dynamic reprompts, which is out of scope for the v2 upgrade I'm currently working on.

**Comment by joelhegg** [comment]
Looking at the following `richInitialPrompt` is hardcoded where `initialPrompts` and `noInputPrompts` need to be. https://github.com/actions-on-google/actions-on-google-nodejs/blob/d7ef56e0bb2c5e6fe3439a4c0198141c57136f44/src/service/actionssdk/conv.ts#L102-L104

I ended up doing this:
```
  const rawResponse: GoogleActionsV2AppResponse = {
    expectUserResponse: true,
    expectedInputs: [{
      inputPrompt: {
        initialPrompts: [{textToSpeech: 'This is the initial prompt'}],
        noInputPrompts: [
          {textToSpeech: 'This is no-input prompt 1'},
          {textToSpeech: 'This is no-input prompt 2'},
          {textToSpeech: 'This is the final prompt'},
        ]
      },
      possibleIntents: [{
        intent: 'actions.intent.TEXT'
      }]
    }]
  };

  conv.json(rawResponse);
```
Seems kind of hacky. Is there a better supported way?

**Comment by yoichiro** [comment]
@joelhegg As the [document](https://developers.google.com/actions/assistant/reprompts) about Reprompts, you need to use the `actions_intent_NO_INPUT` intent to process for reprompts. That is, we should recognize that the Static reprompts feature has been deprecated.

**Comment by joelhegg** [comment]
@yoichiro I haven't seen anything official from Google yet to suggest static reprompts have been deprecated. Given that static reprompts were featured prominently in the v1 library and samples, and dynamic reprompts were only added 9 months ago (https://github.com/actions-on-google/actions-on-google-nodejs/commit/f39d9fa2f58ec1e8ebb5fc0cc3fecfaa02aa01cb), I'd be surprised if this wasn't just a miss in the initial v2 implementation. Migration from static to dynamic reprompts would have been a significant blocker for us in migrating to the v2 library if I didn't figure out the work around.

**Comment by igilham** [comment]
The documentation for the JSON API does not say the static `noInputPrompts` are deprecated. I'd appreciate an answer from Google on this one.

**Comment by yoichiro** [comment]
@joelhegg @igilham Thank you guys for the comments. Actually, I could not find any mentions from documents which the static reprompts is deprecated, too. It seems that I was misunderstanding, sorry. As you mentioned, we need to ask Google whether the static reprompt is deprecated or not. But, probably, I guess that the static reprompts is still alive (see [here](https://developers.google.com/actions/reference/rest/Shared.Types/AppResponse#InputPrompt)). Instead, at updating the sdk from v1 to v2, the feature to support the static reprompts was dropped (because the person in charge forgot?). I guess that it is the fact.

@Canain Could you confirm whether the static reprompts feature is still alive or has already been deprecated?

I think that we will be able to support the static reprompts feature in the sdk v2 again. I intend to post a proposal to support it and send a pull request for it.

**Comment by Canain** [comment]
For the v2 release, we decided to promote dynamic reprompts as they are much more powerful and flexible compared to static no inputs. This was in addition to the fact that static no inputs are very different from other responses and thus was hard to implement a satisfactory API.

Thanks for the feedback. We can add it to v2 but will need to figure out a good API flow that makes sense with the existing response API.

**Comment by Canain** [comment]
Closing this now that a PR supporting this has been merged.
