### ISSUE TITLE
why can't intents wtih i18n by async?

### ISSUE THREAD

**Issue by nealrs** [actions-on-google/actions-on-google-nodejs#183]
I'm currently researching how to internationalize my Action and most of the info seems pretty clear. 

However, according to the [fulfillments section of the localization docs](https://developers.google.com/actions/localization/fulfillment), intents that use the `i18n` node package must not be async. 

Can someone please explain why? My welcome intent relies on `async/await`, but I'd like to use i18n middleware to handle locales. Has anyone tried this with `i18next` (used in Alexa examples)?

**Comment by Canain** [comment]
The current [`i18n`](https://github.com/mashpie/i18n-node) library we mention in the docs only has a shared global instance for setting the locale so it needs to not be async in order to ensure that there are no race conditions with multiple conversations setting conflicting locales.

You should be able to apply the same concepts described in the docs for another i18n library that is able to have multiple concurrent instances with different locales so you can avoid the race condition.

Thank you for bringing up the `i18next` library though! We been wanting to update our localization docs so we'll take a look again at libraries like `18next` to evaluate the best i18n solution for Actions Node.js developers.

**Comment by nealrs** [comment]
Thanks @Canain! My fulfillment is built as an express app hosted on AWS lambda - so the lifetime of the process is only as long as `request => response`. In this case, do you still think I'd run up against the race condition?

**Comment by Canain** [comment]
I'm not super familiar with how AWS Lambda runtimes work exactly, but if you can guarantee that only one conversation request will be invoked at a time for a Node.js instance, then you should be able to avoid the race condition as the locale won't be set multiple times during a single request.

**Comment by Griffinx** [comment]
@nealrs Would you mind sharing some code showing how your welcome intent uses async/await

**Comment by Canain** [comment]
Closing this since the original question was answered.
