### ISSUE TITLE
multiple conv.ask not working with permissions

### ISSUE THREAD

**Issue by homtec** [actions-on-google/actions-on-google-nodejs#206]
Hi, if I request a permission, the previous ask command is ignored. 

In this example, the users gets only the permission request, not the welcome message. 

```
conv.ask('Hi, welcome!')

const options = {
  context: i18n.__('LOCATION_PERMISSION'),
  permissions: ['DEVICE_PRECISE_LOCATION'],
};
conv.ask(new Permission(options));
```
You will only hear the welcome message if you remove the permission request. How to fix this?

**Comment by Fleker** [comment]
If you are asking for permission, that supersedes any general text. If you want to talk to the user, you should do that and only request location when needed.

**Comment by OpenDog** [comment]
Are there any more options to tweak the wording with the helpers (permission, sign-in, surface change, etc)? My problem is for instance the age verification. I use a simple implicit oath flow, with a "are older than 21" question + Y/N buttons. Google keeps calling it account linking "you need to link your account ....". Very annoying.

**Comment by Fleker** [comment]
If you want to do account linking and a separate question for age verification, they should be two steps of the conversation.

> You need to link your account
*Links*
> Thanks Nick. Before we continue, are you over 21?
*Yes*
> Great, thanks. Now let's get started.

**Comment by homtec** [comment]
Ok thank you, I didn't see that in the docs.

I need to find a way to talk to the user before asking for permission. So I
have to create two separate intents with a forwarding?


Nick <notifications@github.com> schrieb am Do., 2. Aug. 2018, 20:31:

**Comment by Fleker** [comment]
You would use two intents, yes, and make it conversational such that the user goes to the second intent.

**Comment by smholsen** [comment]
This is also the case when asking for Confirmations. 
So when you have completed for example a routine (a game or whatever) you may want to ask the user whether he wants go go again, which would be a confirmation prompt. 
What would be the preferred way of going about doing that? Should I here set a context flag about confirmation and use that to guide it to the next intent via the context flag?

Intuitively I would like to finish up the routine in one ask, and then do a new ask with confirmation about whether the user wants to go again, but that won't work, since the first ask would be ignored. If I do the entire response in one Confirmation ask, then that would lead to the response also being included in re-prompts if the confirmation response from the user is not understood on the first go.

Thanks for the amazing work on this project! :)
