### ISSUE TITLE
library should help enforce simple response before Basic Card

### ISSUE THREAD

**Issue by ekeitho** [actions-on-google/actions-on-google-nodejs#207]
i ran into an issue where the assistant kept dropping the conversation when sending a Basic Card without any previous conv.ask in the current session.

#125 was helpful in finding that I had to send at least one simple response before the card. 
it would of been great if there was a helpful error log to state this. :)

**Comment by Canain** [comment]
As the library mainly involves generating JSON, ideally the simulator/platform should show a better error message rather than the library as it would be hard to keep everything synced up (also this isn't any errors on the library itself, just what the platform requires).

We will work on improving the debugging experience for this.
