### ISSUE TITLE
Using media response finished to play another mp3

### ISSUE THREAD

**Issue by CoreyCole** [actions-on-google/actions-on-google-nodejs#247]
Hello, I have a skill on Amazon Alexa that I'm now attempting to port over to actions on google. At the core of my skill, I'm using the audio player to continuously play mp3 files back-to-back. When one mp3 is about to finish, I enqueue the next one. Playback continues until the user pauses or stops the audio player or logs out from my skill.

I'm wondering if this is possible with actions on google. It looks like from #103 I currently need to interrupt the smooth flow from mp3-to-mp3 with some sort of simple response. That is not ideal, but it is not a deal breaker.

Two questions I have that I couldn't find here or in the documentation:
- Is there a minimum length of audio I can play in a media response?
- Can I respond to `actions.intent.MEDIA_STATUS` where the status is `FINISHED` with another media response? This will keep my playback going as I described above.

**Comment by BoneGoat** [comment]
Do note tough that you need to keep the conversation open by using conv.ask(). Otherwise you will not receive the MEDIA_STATUS event when the audio has finished playing. By keeping the conversation open the user will not be able to use system commands like raising or lowering the volume, or set a timer, etc. I have reported this issue several times to Google via partner support but thus far this issue hasn't been fixed.

**Comment by CoreyCole** [comment]
@BoneGoat if the conversation is open, the user cannot use system command, but can they invoke intents in my action while the audio is looping?

**Comment by BoneGoat** [comment]
@CoreyCole Yes.

**Comment by maaaaaaaax** [comment]
Due to more than 4 months of inactivity, this issue is being closed. 

If you think the resolution is in error, please re-open the request with fresh information.
