### ISSUE TITLE
deploying github-app(probot) has issues using google cli

### ISSUE THREAD

**Issue by rthadur** [actions-on-google/actions-on-google-nodejs#282]
Hi 
Iam getting following error while deploying my probot app using google cli 

command : gcloud functions deploy app --runtime nodejs8
error: ERROR: (gcloud.functions.deploy) OperationError: code=3, message=Function failed on loading user code. Error message: Node.js module defined by file index.js is expected to export function named app
iam following instructions here to deploy probot in GCF : https://probot.github.io/docs/serverless-deployment/#google-cloud-function

could you please help me in resolving this issue

**Comment by Fleker** [comment]
Most of our instructions recommend using the Firebase CLI for deploying functions. While using gcloud will work, it may require a slight refactoring of your function for it to work with gcloud.

For example, in [the docs](https://cloud.google.com/functions/docs/writing/http), instead of the Firebase headers, you'd just export the function.
