### ISSUE TITLE
Actions on google not responding properly to HTTP 401

### ISSUE THREAD

**Issue by adambezecny** [actions-on-google/actions-on-google-nodejs#288]
hi,

my google action is using OAUth account linking. When I revoke issued access token (before it expires, e.g. user decides to revoke it) I am sending as a response to subsequent AoG request HTTP 401 with json payload:
{
    "error": "user_not_found"
}

Google assistant just responds <Skill name> isn't responding now. Try again soon. 

I would expect it either to get new access token (using refresh token which is still in place) or redirect to my authorization/login page. 

Does AoG support getting new refresh token or reauthorizing before original access token expiry (e.g. in case it was revoked by the user)?

**Comment by ataillefer** [comment]
Hi,

The fact that the Google assistant leaves the conversation and responds with "isn't responding at the moment. Try again soon." is a bug tracked by #289.

When receiving a 401 status code, the expected behavior is just to unlink your account, which results in `conv.user.access.token` being emptied (it was previously storing the access token obtained through the OAuth 2 sign in process). So, from what I've seen, it is not supposed to try to get a new access token nor to launch the account linking again automatically.

Finally, according to https://developers.google.com/actions/identity/oauth2?oauth=code#handle_token_exchange_requests:
> Google stores the access token and the refresh token for the user and records the expiration of the access token. When the access token expires, Google uses the refresh token to get a new access token from your token exchange endpoint.

So there are 2 cases:
- Your access token has expired: the next time you invoke your action, AoG will try get a new access token with the refresh token previously obtained (AoG it is aware of the expiration time).
- Your access token has been revoked: AoG won't be informed about it so you need to handle the fact of letting the user sign in again to obtain a new token.

Hope this helps!
