### ISSUE TITLE
Code Migration from V1 to V2

### ISSUE THREAD

**Issue by Abhishek9634** [actions-on-google/actions-on-google-nodejs#321]
https://stackoverflow.com/questions/55915929/node-js-google-cloud-functions-merge-location-and-chat-code-i-e-handle-2-agent

As shown above link there are 2 types of code, how we can change 1st one to V2

**Comment by Abhishek9634** [comment]
@Fleker : Can you support here, urgently needed

**Comment by maaaaaaaax** [comment]
Github issues are intended to highlight and resolve current issues with Actions on Google's client libraries. Since this seems more like a code review, please continue this conversation on Stack Overflow (https://stackoverflow.com/questions/tagged/actions-on-google) or Reddit (https://www.reddit.com/r/GoogleAssistantDev).
