### ISSUE TITLE
Get Intent gets action, not Intent

### ISSUE THREAD

**Issue by saffy** [actions-on-google/actions-on-google-nodejs#44]
https://github.com/actions-on-google/actions-on-google-nodejs/blob/63d2a6f5a375db72ce66a9ada9aae4c51a2d657c/api-ai-app.js#L959

Intent name is underneath metadata.intentName, this method name is misleading.

**Comment by HerrPfister** [comment]
Right now I am circumnavigating this with a hack. Before I initialize `ApiAiApp` I do:

```
request.body.result.action = request.body.result.action || request.body.result.metadata.intentName
```

which is awful, and should be fixed, but it has been working.

**Comment by OpenDog** [comment]
I'm doing exactly the same. I fish it out from the payload.

**Comment by OpenDog** [comment]
I forget to add. It seems this is a problem only with "barge-ins".

**Comment by Canain** [comment]
Thanks for the feedback.

In [v2 of the library](https://medium.com/@silvano.luciani/actions-on-google-client-library-for-node-js-v2-0-0-alpha-c92361167f15), we more clearly separated the abstractions between Actions SDK and Dialogflow so naming is clearer for stuff like this. Also in v2, we use the Dialogflow intent name instead of action name to simplify the development experience. There's a [thread](https://github.com/dialogflow/dialogflow-fulfillment-nodejs/issues/9) about this in Dialogflow's GitHub for further discussions.

Let us know of any feedback so we polish it up during the alpha phase.
