### ISSUE TITLE
displayText is never set at root of response

### ISSUE THREAD

**Issue by neckaros** [actions-on-google/actions-on-google-nodejs#59]
Hello,

I'm using dialogflow-app v1.5

When doing a tell:

I expect the reponse to match dialog flow expected reponse and add a displayText and a speech:
from: https://dialogflow.com/docs/fulfillment#response
```
Body:
{
"speech": "Barack Hussein Obama II was the 44th and current President of the United States.",
"displayText": "Barack Hussein Obama II was the 44th and current President of the United States, and the first African American to hold the office. Born in Honolulu, Hawaii, Obama is a graduate of Columbia University   and Harvard Law School, where ",
"data": {...},
"contextOut": [...],
"source": "DuckDuckGo"
}
```

but when i do:
```
assistant.tell({speech: 'Great see you at your appointment!',
             displayText: 'Great, we will see you on '});
```

displayText is not set in the reponse:
```
{
   "speech":"Great see you at your appointment!",
   "contextOut":[
      {
         "name":"downloadslist",
         "lifespan":5,
         "parameters":{         }
      }
   ],
   "data":{
      "google":{
         "expect_user_response":false,
         "rich_response":{
            "items":[
               {
                  "simple_response":{
                     "text_to_speech":"Great see you at your appointment!",
                     "display_text":"Great, we will see you on "
                  }
               }
            ],
            "suggestions":[            ]
         },
         "no_input_prompts":[         ]
      }
   }
}
```

**Comment by Canain** [comment]
Hey there, thanks for the feedback!

Is there a specific use case you need the `displayText` to be at the root of the response?

The goal of the client library is to support development for Actions on Google with the ability to use Dialogflow for natural language understanding but the response is meant to be passed through Dialogflow directly to the Google Assistant.

So besides Dialogflow non-response fields for NLU support like contexts, really only the `data` field is meant to be set. The main issue this could cause is that the Dialogflow simulator might not behave as expected, but because the Dialogflow simulator is meant for Dialogflow specific stuff (only text responses) and does not render Actions on Google responses, it is not supported.

**Comment by Canain** [comment]
Closing this issue for now since there hasn't been any updates.

Please reopen if you have any more questions or concerns.
