### ISSUE TITLE
Add Smart Home functionality

### ISSUE THREAD

**Issue by WeeJeWel** [actions-on-google/actions-on-google-nodejs#89]
As stated in the [docs](https://developers.google.com/actions/smarthome/create-app):

```
Note: The Node.js 'actions-on-google' client library does not currently support Smart Home apps.
```

It would of course be a lot easier if this were supported.

**Comment by Canain** [comment]
Smart Home support has now been added in 186b108d7cdca0425b856a42272dc3b9cd1c12ee

So any release since [`2.1.0`](https://github.com/actions-on-google/actions-on-google-nodejs/releases/tag/v2.1.0) should support the Smart Home service.

Check out the [README](https://github.com/actions-on-google/actions-on-google-nodejs) for some snippets on how to use it.
