### ISSUE TITLE
use debug message instead of error

### ISSUE THREAD

**Issue by liuxiao** [actions-on-google/actions-on-google-nodejs#99]
https://github.com/actions-on-google/actions-on-google-nodejs/blob/be754b76139bce22aee80b6eef19b6d70f70486a/assistant-app.js#L2475

Use debug message instead of error when the object does not exist. There is no functional impact, but will be distracting error message from cloud function log/firebase log console.

**Comment by smishra2** [comment]
I agree that generally the error messages can clutter the logs, but in which cases is userStorage not a part of the request to the webhook? If we change the message level here, it'd be inconsistent with similar "errors" elsewhere in the code. I imagine we'd have to change it everywhere?

**Comment by yoichiro** [comment]
@smishra2 I think that this is a critical bug. Basically, I think that the user object is passed always. However, currently, actions on google sometimes sends a request without the userStorage object. And, when the request doesn't have the userStorage object, this actions-on-google-nodejs sdk is crashed in the `DialogflowApp` constructor by the `error()` call. I guess that many developers have the same problem and cannot use this sdk since 1.8.2. I expect that this pull request is merged quickly and a fixed version will be released soon.

**Comment by smishra2** [comment]
Hey @yoichiro I've gone ahead and merged the PR, so that should fix the log cluttering issue. But I'm not quite sure why the `DialogflowApp` constructor is crashing from this, since the [error()](https://github.com/actions-on-google/actions-on-google-nodejs/blob/b232fab025226484b9e7d210ad2d4a2ed3ee4c44/assistant-app.js#L21) call is only a logging function, nothing else. 

I'd recommend opening a new issue, and it'd be helpful to maybe see some more helpful debugging info, like the logs you're seeing when the constructor call crashes.

**Comment by yoichiro** [comment]
@smishra2 I got something wrong. As your mention, yes, there may be an other reason to crash I encountered. Thank you for the description.
